name: Create Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build_tag:
    if: github.event.pull_request.merged == true
    name: Bump version and push new tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Bump version & push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
      
      - name: Examine new tag
        run: |
          echo "New tag: ${{ steps.tag_version.outputs.new_tag }}"

  release:
    needs: [build_tag]
    ## if: ${{ needs.build_tag.outputs.new_tag != '' }}
    name: Create release from tag
    runs-on: ubuntu-latest
    steps:
      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ job.build_tag.steps.tag_version.outputs.new_tag }}
          name: ${{ job.build_tag.steps.tag_version.outputs.new_tag }}
          body: ${{ job.build_tag.steps.tag_version.outputs.changelog }}
          # Custom token scope must be set to 'repo'; this includes every child option to 'repo'
          token: ${{ secrets.CLOUD_WEBSITE_PROJECT_GITHUB_TOKEN }}

# Tag naming via commits:
#   fix:[commit_message] #- patch
#   feat:[commit_messge] #- minor
#   BREAKING CHANGE:[commit_message] #- major