name: Deploy to the Cloud

on:
  release:
    types: [published]

jobs:
  test_branch:
    name: Test branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        env:
          LOGIN_SIGNUP_SECRET_KEY: ${{ secrets.LOGIN_SIGNUP_SECRET_KEY }}
        run: python -m pytest

  deploy:
    name: Deploying onto Cloud
    runs-on: ubuntu-latest
    needs: [test_branch]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "itsc-3155-group-1-website" # Must be unique in Heroku
          heroku_email: "uzochidimkpa@gmail.com"